# Generated by Django 2.2 on 2020-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
