# Generated by Django 2.2 on 2020-01-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200111_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
