# Generated by Django 2.2 on 2020-01-09 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Bajor'), (2, 'Monkey'), (3, 'Bear')], max_length=50)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('date_arrived', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_visit', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.Animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateTimeField(auto_now_add=True)),
                ('date_duration', models.DateTimeField(default=datetime.datetime(2020, 1, 10, 20, 58, 12, 653440))),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Visitor')),
            ],
        ),
    ]
