# Generated by Django 2.2 on 2020-01-09 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('1', 'Bajor'), ('2', 'Monkey'), ('3', 'Bear')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_duration',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 21, 6, 47, 228770)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=20),
        ),
    ]
