# Generated by Django 2.2 on 2020-01-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail_info', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('count_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='', null=True, upload_to='')),
                ('profile_wallet', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_items', models.IntegerField(default=0)),
                ('event_date_time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReversalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date_time', models.DateTimeField(auto_now_add=True)),
                ('shopping_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ShoppingEvent')),
            ],
        ),
    ]
