# Generated by Django 2.2 on 2020-01-19 21:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200119_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='shoppingevent',
            name='count_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
