# Generated by Django 2.2 on 2020-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_shoppingevent_flag_reversal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingevent',
            name='flag_reversal',
        ),
        migrations.AddField(
            model_name='reversalevent',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
