# Generated by Django 2.2 on 2020-01-26 21:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200126_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingevent',
            name='order_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
